### ISSUE TITLE
Installation requires pytest-runner

### ISSUE THREAD

**Issue by jwiggins** [PyCQA/mccabe#54]
It would be nice if `setup.py` implemented the conditional requirement suggested by pytest-runner: https://github.com/pytest-dev/pytest-runner#conditional-requirement

**Comment by sigmavirus24** [comment]
I'd accept a Pull Request that implements that.

That said, this is a low priority for me (and only me) for a few reasons:

1. We ship universal wheels which mean that anyone with a remotely modern version of pip will get the wheel and never see this.
2. I've been harangued in the past by downstream redistributors for not putting this there because they want every package to use `python setup.py test` - an antiquated an terrible interface for running test.
3. This should only be a problem if you use `--no-binary :all:` with pip or have a tool that doesn't install wheels.

**Comment by jwiggins** [comment]
Okie dokie. I'm basically coming at this from situation 3, installing from the PyPI sdist tarball on a machine with no connection to the outside world. A bit special... I know.

**Comment by sigmavirus24** [comment]
> Okie dokie. I'm basically coming at this from situation 3, installing from the PyPI sdist tarball on a machine with no connection to the outside world. A bit special... I know.

Could you provide some context around why? I'm curious since this tends to be something people making system packages do, but they also tend to want to run the tests and have the necessary packages to do so.

**Comment by jwiggins** [comment]
I'm building a control system which contains a large number of 3rd party packages which have a known dependency hierarchy. It's completely self-contained and meant to be built on infrastructure that doesn't necessarily have a connection to the internet. We have pytest already, but mccabe is the first package which requires pytest-runner (and it's not a hard requirement).
